language: node_js
node_js: lts/*
sudo: required
cache: yarn
script:
- commitlint-travis
deploy:
  provider: script
  script:
  - npx semantic-release
  on:
    branch: master
env:
  global:
  - secure: c2AxKox9rNHpU83jN8Bfq99NDq6HgDSpeLodToAY8i5n4UyhdHr2uFXUw3zaUxDoUzCLR2fkfGX4VKxf4EPYHIb6KqtIj2OzEOBE3xvDK2yHx+pfyZZF01Pk+gGcwtM0PRyrxLbEB/gkvNtlVJMHZPc3Z0HK8VidjZKvCWR/9emRE3ezm+nj3z7qajkrd0o5qlT0AP8JBCXEukpwXvHMc36pBopAK2EE+xbfeKTxSkrVf+Jf222POLR55BE83Wr/sgpyf16gCfiX+CVlF++icmnuBXxg8Vc0/lzyacsNiYA1Pil81rwbksD7h4IoAW7/V7nHlBM5bPerQ94387x+eC6DgtZZTEsdSrpZ4liIvskNcfIfg+vsbACe2TVYipFTgfJy81OUBhaLspl8lfrl2TIPIhQ7ree2FjwbdGAs7Mo0lMyPNhIUHbxnq3m1IseUR6m6BwqJ1GGxjiNKqgixQtU35lCPDx/COk2owv2t6HWC9BGuILYbj1Z01uRjAxCay+pouNQlaxvlBd1JYQZWRryPfGtARCZODFQklmlAtrP1bFUMJJ3AFywyH5twUDYa4wMKto0oI8uYWLT6NyjNos1YsNBN0XUJQuBMd1fLj+FSDBU0goVICrVnS5UzWaaZZYpXeWGWnFfk79k2Hijqr6Jrb/yhBPCAO0XdwwNV9/U=
  - secure: 0ZsiwfISmP55ShNO/K34j1OCpLdXukIeBNyE8FFjiEf9NMzfRVffzQnj3xizhJNQRo6XRVb3VRyZ0NExqurtV9az+Yq+H3h3UpPE6M2Ai3dSk+i7fwwO/lE1lcduYetci49zL9s9pygOp3p+hiUXZlUxjCGLHNGeBt3PEEC7XaAD/Je2a7UTeXqerLmUcN8AI3bQaWtp+6F7DQO1pBU1FLWEW5jcTG9fI4b+4vJmEZyEMbfijVnc4Npb6QVWVr49lugh/S2EY71f/s/gEdu2I7lDDajo1HjoYuWEsSFgt109sTp6IUHDMI2YiZ1BYk9Kx8nb1DLOkblASZhtPwEf7KMAgnS91tAjBC9TWULqjkqprsC0tsxzrrQePfoyb9iZPSgp4akBERmRqnZ31BAeNAoGMyEyX5J9pMxzGZJPr206MJNEiWGL9dSOUlJRMMwGfdDKI453G6ZH3v4U3N1nTKyxcPSyhTSvnh00GvpRUaQZu/kmc6ZxMb0/aWRucvnLkhDV5sWUMVjr+OTAJaSWJOjTe1h98CIgXEXQnjdhO6LRso7qHlB+ot6OkWqsA9sxIwUYUlow9xR2C4eV9rOnt7lQ7yjev2WxgIYTwLHdOIGzwIYVNqOKaLWFgh0SGfRt3oF7IykOElp7/v729sjZfk/vdaeJfyv3IP3lcyHFAqs=
